### ISSUE TITLE
Long integers not encoded when inside dict

### ISSUE THREAD

**Issue by willemt** [plasmashadow/pytorrent#1]
Hi thanks for the library!

I found an issue when encoding longs when they are enclosed in dicts.

```
>>> bencode.Bencoder.encode({'x': 9223372036854775808})
'd1:x9223372036854775808e'
```

Expected:

```
'd1:xi9223372036854775808ee'
```

Interesting that it works when the int isn't enclosed within the dict:

```
>>> bencode.Bencoder.encode(9223372036854775808)
'i9223372036854775808e'
```

**Comment by sourcepirate** [comment]
Hi @willemt 
Thanks for the Information I will fix it soon.

**Comment by willemt** [comment]
thanks for fixing it
